In [1]:
import cv2
import sys
import numpy as np

In [64]:
arucodict = cv2.aruco.Dictionary_get(0)
arucoParams = cv2.aruco.DetectorParameters_create()

coord_dict = {7:np.array([(0,20,0),
                         (20,20,0),
                         (20,0,0),
                         (0,0,0)]),
            6:np.array([(0,20,-90),
                         (20,20,-90),
                         (20,0,-90),
                         (0,0,-90)]),
            10:np.array([(0,20,-180),
                         (20,20,-180),
                         (20,0,-180),
                         (0,0,-180)]),
            0:np.array([(0,20,-270),
                         (20,20,-270),
                         (20,0,-270),
                         (0,0,-270)])}

K = np.array([[900,0,960],
             [0,900,540],
             [0,0,1]]).astype(np.float32)
dist_coeffs = np.zeros((4,1))

In [98]:
cap = cv2.VideoCapture('t_3-edit.mp4')

pose = [[0],[0],[0]]
rot = [[0],[0],[0]]

while(cap.isOpened()):
  ret, frame = cap.read()
  corners, ids, rejected = cv2.aruco.detectMarkers(frame,arucodict, parameters=arucoParams)
  objp = [0,0,0]
  imgp = [0,0]
  if len(corners) > 0:
    # flatten the ArUco IDs list
    ids = ids.flatten()
    # loop over the detected ArUCo corners
    for (markerCorner, markerID) in zip(corners, ids):
        # extract the marker corners (which are always returned
        # in top-left, top-right, bottom-right, and bottom-left
        # order)
        corners = markerCorner.reshape((4, 2))
        (topLeft, topRight, bottomRight, bottomLeft) = corners
        
        if(topRight[0]-topLeft[0]<0):
            topLeft,bottomRight = bottomRight,topLeft
            topRight,bottomLeft = bottomLeft,topRight
        
        objp = np.vstack([objp,coord_dict[markerID]])
        imgp = np.vstack([imgp,(topLeft, topRight, bottomRight, bottomLeft)])
        print(coord_dict[markerID])
        print((topLeft, topRight, bottomRight, bottomLeft))
        print('________________')
            
        # convert each of the (x, y)-coordinate pairs to integers
        topRight = (int(topRight[0]), int(topRight[1]))
        bottomRight = (int(bottomRight[0]), int(bottomRight[1]))
        bottomLeft = (int(bottomLeft[0]), int(bottomLeft[1]))
        topLeft = (int(topLeft[0]), int(topLeft[1]))
    
        # draw the bounding box of the ArUCo detection
        cv2.line(frame, topLeft, topRight, (0, 255, 0), 2)
        cv2.line(frame, topRight, bottomRight, (255, 0, 0), 2)
        cv2.line(frame, bottomRight, bottomLeft, (0, 0, 255), 2)
        cv2.line(frame, bottomLeft, topLeft, (0, 255, 255), 2)
        # compute and draw the center (x, y)-coordinates of the
        # ArUco marker
        cX = int((topLeft[0] + bottomRight[0]) / 2.0)
        cY = int((topLeft[1] + bottomRight[1]) / 2.0)
        cv2.circle(frame, (cX, cY), 4, (0, 0, 255), -1)
        # draw the ArUco marker ID on the frame
        cv2.putText(frame, str(markerID),
            (topLeft[0], topLeft[1] - 15),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.5, (0, 255, 0), 2)
    success, rotation_vector, translation_vector = cv2.solvePnP(objp[1:,:].astype(np.float32), 
                                                                    imgp[1:,:].astype(np.float32),
                                                                    K, dist_coeffs, flags=0)
    pose = np.hstack([pose,translation_vector])
    rot = np.hstack([rot,rotation_vector])
        
    # show the output frame
    cv2.imshow("Frame", frame)
    key = cv2.waitKey(1) & 0xFF
    # if the `q` key was pressed, break from the loop
    if key == ord("q"):
        break
          
# do a bit of cleanup
cv2.destroyAllWindows()

cap.release()

[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([768., 553.], dtype=float32), array([900., 541.], dtype=float32), array([911., 688.], dtype=float32), array([779., 699.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([573., 547.], dtype=float32), array([759., 531.], dtype=float32), array([773., 721.], dtype=float32), array([588., 735.], dtype=float32))
________________
[[ 0 20  0]
 [20 20  0]
 [20  0  0]
 [ 0  0  0]]
(array([241., 536.], dtype=float32), array([492., 516.], dtype=float32), array([507., 788.], dtype=float32), array([256., 798.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([764., 552.], dtype=float32), array([897., 539.], dtype=float32), array([910., 687.], dtype=float32), array([776., 699.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([571., 544.], dtype=float32)

[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([775., 556.], dtype=float32), array([911., 545.], dtype=float32), array([923., 695.], dtype=float32), array([785., 706.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([575., 549.], dtype=float32), array([764., 533.], dtype=float32), array([780., 729.], dtype=float32), array([590., 742.], dtype=float32))
________________
[[ 0 20  0]
 [20 20  0]
 [20  0  0]
 [ 0  0  0]]
(array([229., 538.], dtype=float32), array([486., 518.], dtype=float32), array([502., 799.], dtype=float32), array([246., 810.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([773., 558.], dtype=float32), array([910., 545.], dtype=float32), array([923., 696.], dtype=float32), array([784., 707.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([573., 548.], dtype=float32)

[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([753., 571.], dtype=float32), array([897., 557.], dtype=float32), array([910., 713.], dtype=float32), array([764., 725.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([547., 560.], dtype=float32), array([744., 544.], dtype=float32), array([759., 750.], dtype=float32), array([562., 762.], dtype=float32))
________________
[[ 0 20  0]
 [20 20  0]
 [20  0  0]
 [ 0  0  0]]
(array([170., 545.], dtype=float32), array([441., 525.], dtype=float32), array([457., 826.], dtype=float32), array([188., 835.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([756., 570.], dtype=float32), array([901., 557.], dtype=float32), array([913., 713.], dtype=float32), array([767., 725.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([548., 560.], dtype=float32)

[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([754., 568.], dtype=float32), array([906., 554.], dtype=float32), array([919., 713.], dtype=float32), array([767., 727.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([541., 557.], dtype=float32), array([744., 540.], dtype=float32), array([761., 753.], dtype=float32), array([557., 765.], dtype=float32))
________________
[[ 0 20  0]
 [20 20  0]
 [20  0  0]
 [ 0  0  0]]
(array([139., 542.], dtype=float32), array([422., 521.], dtype=float32), array([438., 835.], dtype=float32), array([160., 847.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([757., 568.], dtype=float32), array([910., 555.], dtype=float32), array([923., 715.], dtype=float32), array([769., 727.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([542., 558.], dtype=float32)

[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([723., 576.], dtype=float32), array([883., 563.], dtype=float32), array([898., 728.], dtype=float32), array([736., 741.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([501., 564.], dtype=float32), array([712., 546.], dtype=float32), array([730., 769.], dtype=float32), array([519., 782.], dtype=float32))
________________
[[ 0 20  0]
 [20 20  0]
 [20  0  0]
 [ 0  0  0]]
(array([ 66., 546.], dtype=float32), array([362., 523.], dtype=float32), array([380., 858.], dtype=float32), array([ 86., 866.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([721., 577.], dtype=float32), array([882., 562.], dtype=float32), array([896., 727.], dtype=float32), array([735., 742.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([499., 564.], dtype=float32)

[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([711., 578.], dtype=float32), array([875., 562.], dtype=float32), array([890., 732.], dtype=float32), array([725., 745.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([479., 562.], dtype=float32), array([697., 543.], dtype=float32), array([715., 777.], dtype=float32), array([496., 788.], dtype=float32))
________________
[[ 0 20  0]
 [20 20  0]
 [20  0  0]
 [ 0  0  0]]
(array([ 13., 539.], dtype=float32), array([323., 516.], dtype=float32), array([339., 870.], dtype=float32), array([ 33., 878.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([711., 576.], dtype=float32), array([878., 562.], dtype=float32), array([891., 732.], dtype=float32), array([724., 743.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([478., 561.], dtype=float32)

[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([711., 565.], dtype=float32), array([883., 550.], dtype=float32), array([899., 725.], dtype=float32), array([727., 739.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([463., 550.], dtype=float32), array([693., 530.], dtype=float32), array([712., 773.], dtype=float32), array([483., 786.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([708., 566.], dtype=float32), array([880., 550.], dtype=float32), array([895., 725.], dtype=float32), array([723., 739.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([459., 550.], dtype=float32), array([690., 530.], dtype=float32), array([707., 773.], dtype=float32), array([478., 786.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([703

[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([686., 571.], dtype=float32), array([863., 555.], dtype=float32), array([878., 737.], dtype=float32), array([700., 752.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([420., 552.], dtype=float32), array([660., 533.], dtype=float32), array([678., 788.], dtype=float32), array([438., 802.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([688., 569.], dtype=float32), array([866., 555.], dtype=float32), array([882., 736.], dtype=float32), array([703., 750.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([422., 553.], dtype=float32), array([663., 532.], dtype=float32), array([682., 787.], dtype=float32), array([440., 801.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([690

[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([685., 563.], dtype=float32), array([868., 547.], dtype=float32), array([883., 736.], dtype=float32), array([699., 750.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([401., 543.], dtype=float32), array([653., 521.], dtype=float32), array([672., 789.], dtype=float32), array([421., 803.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([680., 562.], dtype=float32), array([865., 547.], dtype=float32), array([881., 736.], dtype=float32), array([696., 749.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([394., 543.], dtype=float32), array([648., 521.], dtype=float32), array([670., 789.], dtype=float32), array([417., 804.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([674

[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([643., 555.], dtype=float32), array([832., 537.], dtype=float32), array([849., 734.], dtype=float32), array([659., 748.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([338., 534.], dtype=float32), array([601., 511.], dtype=float32), array([623., 792.], dtype=float32), array([359., 807.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([638., 554.], dtype=float32), array([829., 536.], dtype=float32), array([846., 734.], dtype=float32), array([656., 748.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([332., 535.], dtype=float32), array([596., 509.], dtype=float32), array([619., 792.], dtype=float32), array([354., 808.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([639

[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([621., 559.], dtype=float32), array([818., 541.], dtype=float32), array([836., 746.], dtype=float32), array([638., 761.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([292., 536.], dtype=float32), array([568., 510.], dtype=float32), array([592., 808.], dtype=float32), array([314., 824.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([620., 558.], dtype=float32), array([817., 539.], dtype=float32), array([835., 746.], dtype=float32), array([636., 760.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([289., 534.], dtype=float32), array([567., 509.], dtype=float32), array([590., 808.], dtype=float32), array([313., 824.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([617

[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([576., 550.], dtype=float32), array([780., 532.], dtype=float32), array([799., 745.], dtype=float32), array([592., 757.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([222., 524.], dtype=float32), array([513., 497.], dtype=float32), array([539., 812.], dtype=float32), array([246., 827.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([575., 549.], dtype=float32), array([778., 530.], dtype=float32), array([798., 746.], dtype=float32), array([592., 761.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([219., 524.], dtype=float32), array([511., 498.], dtype=float32), array([533., 813.], dtype=float32), array([242., 829.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([573

[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([768., 576.], dtype=float32), array([919., 565.], dtype=float32), array([931., 730.], dtype=float32), array([781., 739.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([542., 546.], dtype=float32), array([756., 525.], dtype=float32), array([775., 747.], dtype=float32), array([560., 765.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([149., 517.], dtype=float32), array([456., 486.], dtype=float32), array([484., 825.], dtype=float32), array([174., 842.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([766., 575.], dtype=float32), array([918., 566.], dtype=float32), array([930., 731.], dtype=float32), array([780., 739.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]

[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([728., 580.], dtype=float32), array([888., 574.], dtype=float32), array([899., 743.], dtype=float32), array([741., 753.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([493., 549.], dtype=float32), array([716., 527.], dtype=float32), array([734., 762.], dtype=float32), array([511., 779.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([ 63., 514.], dtype=float32), array([387., 484.], dtype=float32), array([415., 847.], dtype=float32), array([ 90., 863.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([728., 580.], dtype=float32), array([888., 573.], dtype=float32), array([899., 742.], dtype=float32), array([742., 752.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]

[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([710., 574.], dtype=float32), array([879., 565.], dtype=float32), array([891., 739.], dtype=float32), array([725., 750.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([466., 540.], dtype=float32), array([697., 518.], dtype=float32), array([719., 761.], dtype=float32), array([486., 778.], dtype=float32))
________________
[[  0  20 -90]
 [ 20  20 -90]
 [ 20   0 -90]
 [  0   0 -90]]
(array([  4., 504.], dtype=float32), array([342., 469.], dtype=float32), array([373., 854.], dtype=float32), array([ 35., 871.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([711., 576.], dtype=float32), array([881., 566.], dtype=float32), array([891., 742.], dtype=float32), array([724., 751.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]

[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([678., 580.], dtype=float32), array([860., 570.], dtype=float32), array([871., 750.], dtype=float32), array([692., 759.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([420., 543.], dtype=float32), array([663., 519.], dtype=float32), array([685., 773.], dtype=float32), array([441., 791.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([675., 580.], dtype=float32), array([857., 568.], dtype=float32), array([868., 751.], dtype=float32), array([688., 761.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([417., 542.], dtype=float32), array([660., 518.], dtype=float32), array([682., 775.], dtype=float32), array([438., 793.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0

[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([680., 568.], dtype=float32), array([871., 556.], dtype=float32), array([883., 746.], dtype=float32), array([691., 757.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([395., 527.], dtype=float32), array([656., 500.], dtype=float32), array([681., 774.], dtype=float32), array([420., 792.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([674., 568.], dtype=float32), array([863., 558.], dtype=float32), array([877., 747.], dtype=float32), array([687., 759.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([387., 522.], dtype=float32), array([647., 500.], dtype=float32), array([675., 776.], dtype=float32), array([415., 794.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0

[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([638., 561.], dtype=float32), array([836., 548.], dtype=float32), array([848., 746.], dtype=float32), array([651., 759.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([333., 517.], dtype=float32), array([605., 488.], dtype=float32), array([628., 779.], dtype=float32), array([356., 798.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([638., 561.], dtype=float32), array([837., 549.], dtype=float32), array([850., 746.], dtype=float32), array([652., 760.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([332., 518.], dtype=float32), array([604., 488.], dtype=float32), array([629., 779.], dtype=float32), array([356., 799.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0

[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([617., 564.], dtype=float32), array([822., 552.], dtype=float32), array([835., 758.], dtype=float32), array([629., 770.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([289., 515.], dtype=float32), array([575., 488.], dtype=float32), array([600., 791.], dtype=float32), array([313., 813.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([615., 563.], dtype=float32), array([820., 551.], dtype=float32), array([834., 758.], dtype=float32), array([628., 770.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([285., 516.], dtype=float32), array([572., 485.], dtype=float32), array([598., 792.], dtype=float32), array([310., 813.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0

[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([209., 502.], dtype=float32), array([514., 468.], dtype=float32), array([541., 801.], dtype=float32), array([234., 823.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([574., 557.], dtype=float32), array([793., 544.], dtype=float32), array([805., 761.], dtype=float32), array([588., 773.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([208., 503.], dtype=float32), array([512., 469.], dtype=float32), array([541., 803.], dtype=float32), array([234., 824.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([572., 556.], dtype=float32), array([788., 542.], dtype=float32), array([802., 761.], dtype=float32), array([586., 773.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0

[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([525., 557.], dtype=float32), array([751., 544.], dtype=float32), array([765., 771.], dtype=float32), array([540., 784.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([126., 500.], dtype=float32), array([448., 465.], dtype=float32), array([478., 817.], dtype=float32), array([154., 839.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([520., 558.], dtype=float32), array([745., 545.], dtype=float32), array([761., 773.], dtype=float32), array([535., 785.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([120., 500.], dtype=float32), array([440., 464.], dtype=float32), array([472., 820.], dtype=float32), array([147., 841.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0

[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([496., 552.], dtype=float32), array([731., 539.], dtype=float32), array([745., 775.], dtype=float32), array([512., 789.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([ 63., 488.], dtype=float32), array([400., 450.], dtype=float32), array([430., 829.], dtype=float32), array([ 91., 849.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([499., 552.], dtype=float32), array([735., 538.], dtype=float32), array([748., 776.], dtype=float32), array([513., 788.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([ 64., 485.], dtype=float32), array([402., 448.], dtype=float32), array([432., 828.], dtype=float32), array([ 89., 849.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0

[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([480., 542.], dtype=float32), array([725., 525.], dtype=float32), array([742., 773.], dtype=float32), array([497., 787.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([  3., 471.], dtype=float32), array([361., 429.], dtype=float32), array([395., 834.], dtype=float32), array([ 35., 858.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([480., 539.], dtype=float32), array([726., 524.], dtype=float32), array([742., 773.], dtype=float32), array([496., 786.], dtype=float32))
________________
[[   0   20 -180]
 [  20   20 -180]
 [  20    0 -180]
 [   0    0 -180]]
(array([  6., 473.], dtype=float32), array([352., 433.], dtype=float32), array([387., 828.], dtype=float32), array([ 36., 852.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0

[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([403., 550.], dtype=float32), array([673., 533.], dtype=float32), array([689., 807.], dtype=float32), array([421., 821.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([402., 551.], dtype=float32), array([673., 535.], dtype=float32), array([689., 810.], dtype=float32), array([420., 824.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([401., 551.], dtype=float32), array([672., 534.], dtype=float32), array([688., 810.], dtype=float32), array([419., 823.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([398., 552.], dtype=float32), array([669., 533.], dtype=float32), array([686., 810.], dtype=float32), array([414., 823.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0

[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([281., 556.], dtype=float32), array([581., 536.], dtype=float32), array([601., 844.], dtype=float32), array([302., 859.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([281., 557.], dtype=float32), array([579., 538.], dtype=float32), array([600., 846.], dtype=float32), array([300., 861.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([273., 556.], dtype=float32), array([575., 536.], dtype=float32), array([594., 846.], dtype=float32), array([294., 860.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([267., 555.], dtype=float32), array([569., 535.], dtype=float32), array([589., 847.], dtype=float32), array([290., 861.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0

[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([129., 539.], dtype=float32), array([461., 515.], dtype=float32), array([484., 860.], dtype=float32), array([151., 877.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([128., 537.], dtype=float32), array([463., 513.], dtype=float32), array([486., 862.], dtype=float32), array([151., 879.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([130., 537.], dtype=float32), array([466., 514.], dtype=float32), array([488., 863.], dtype=float32), array([152., 881.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0    0 -270]]
(array([128., 538.], dtype=float32), array([463., 515.], dtype=float32), array([487., 866.], dtype=float32), array([151., 883.], dtype=float32))
________________
[[   0   20 -270]
 [  20   20 -270]
 [  20    0 -270]
 [   0

error: OpenCV(4.6.0) /io/opencv_contrib/modules/aruco/src/aruco.cpp:1097: error: (-215:Assertion failed) !_image.empty() in function 'detectMarkers'


In [96]:
print(rot[2,:])

[ 0.         -0.02472273 -0.02004966 -0.02422451 -0.02893904 -0.02561679
 -0.0257952  -0.02673193 -0.02649129 -0.02744191 -0.03397497 -0.03804122
 -0.04173076 -0.03934368 -0.03924973 -0.03677639 -0.03004516 -0.02381429
 -0.01667074 -0.01343117 -0.01592328 -0.0131594  -0.01407772 -0.02400343
 -0.0307767  -0.02890759 -0.02547972 -0.02818815 -0.02383351 -0.0135169
 -0.00855362 -0.00717749 -0.00907099 -0.01234031 -0.01705622 -0.02349155
 -0.02521433 -0.0252298  -0.02392969 -0.01823775 -0.01272996 -0.00770026
 -0.00485285 -0.00348238 -0.00847016 -0.00451131 -0.01036052 -0.02466631
 -0.02357511 -0.02204596 -0.02662665 -0.02129028 -0.01846705 -0.01099961
  0.00049403  0.00318994  0.00337564  0.00532987  0.00031551 -0.0021314
 -0.00701769 -0.00835279 -0.00498944 -0.00443704  0.00141752  0.01128562
  0.01669435  0.01914508  0.02362313  0.02467667  0.02315267  0.01731581
  0.01296633  0.01149912  0.00640905  0.00708936  0.01061433  0.01689424
  0.02054313  0.02685962  0.03028841  0.03109967  0.0

In [81]:
a,b = b,a

In [23]:
a = [0,0,0,0]
b = np.random.rand(4,4)

In [24]:
np.vstack((a,b))

array([[0.        , 0.        , 0.        , 0.        ],
       [0.31487656, 0.58577576, 0.93284665, 0.71314846],
       [0.81640548, 0.06376371, 0.22980325, 0.44702081],
       [0.95322497, 0.25340214, 0.74738163, 0.09421588],
       [0.08896607, 0.60846572, 0.61127917, 0.43693554]])